[p.x1]
tex = "rjw2"
lt = [  0,   0]
wh = [128, 128]
or = [ 64,  64]

[p.x2]
tex = "rjw2"
lt = [128,   0]
wh = [128, 128]
or = [ 64,  64]

[p.x3]
tex = "rjw2"
lt = [256,   0]
wh = [128, 128]
or = [ 64,  64]

[p.x4]
tex = "rjw2"
lt = [384,   0]
wh = [128, 128]
or = [ 64,  64]

[p.y1]
tex = "rjw2"
lt = [  0, 128]
wh = [128, 128]
or = [ 64,  64]

[p.y2]
tex = "rjw2"
lt = [128, 128]
wh = [128, 128]
or = [ 64,  64]

[p.y3]
tex = "rjw2"
lt = [256, 128]
wh = [128, 128]
or = [ 64,  64]

[p.y4]
tex = "rjw2"
lt = [384, 128]
wh = [128, 128]
or = [ 64,  64]

[p.z]
tex = "rjw2"
lt = [384, 256]
wh = [128, 128]
or = [ 64,  64]

[p.kitty]
tex = "rjw2"
lt = [  0, 256]
wh = [144, 128]
or = [ 96,  64]

[p.tv]
tex = "rjw2"
lt = [156, 256]
wh = [228, 174]
or = [120,  96]